"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useState, useEffect } from "react";
import { techTopics } from "@/data/capitol-pulse";
import { Bill, CongressMember } from "@/lib/capitol-pulse/types";
import { ScrollReveal } from "@/components/ScrollAnimations";

interface BillExplainer {
  oneSentence: string;
  whatItWouldDo: string[];
  whoItAffects: string[];
  whatChanges: string[];
  keyTerms: { term: string; definition: string }[];
  argumentsFor: string[];
  argumentsAgainst: string[];
  whatToWatch: string;
  sourcesUsed: { title: string; url: string }[];
  disclaimers: string[];
}

export default function BillDetailPage() {
  const params = useParams();
  const billId = params.billId as string;
  
  const [loading, setLoading] = useState(true);
  const [bill, setBill] = useState<Bill | null>(null);
  const [sponsor, setSponsor] = useState<CongressMember | null>(null);
  const [cosponsors, setCosponsors] = useState<CongressMember[]>([]);
  const [explainer, setExplainer] = useState<BillExplainer | null>(null);
  const [explainerLoading, setExplainerLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showCosponsors, setShowCosponsors] = useState(false);

  useEffect(() => {
    async function loadBill() {
      try {
        // Fetch bill by ID
        const res = await fetch(`/api/capitol-pulse/bills/${billId}`);
        if (!res.ok) {
          if (res.status === 404) {
            setError("Bill not found");
          } else {
            setError("Failed to load bill");
          }
          return;
        }
        
        const data = await res.json();
        setBill(data.bill);
        
        // Fetch sponsor and cosponsors
        const membersRes = await fetch('/api/capitol-pulse/members');
        const membersData = await membersRes.json();
        const allMembers = membersData.members || [];
        
        if (data.bill?.sponsorBioguideId) {
          const foundSponsor = allMembers.find(
            (m: CongressMember) => m.bioguideId === data.bill.sponsorBioguideId
          );
          setSponsor(foundSponsor || null);
        }
        
        if (data.bill?.cosponsorBioguideIds?.length > 0) {
          const foundCosponsors = allMembers.filter(
            (m: CongressMember) => data.bill.cosponsorBioguideIds.includes(m.bioguideId)
          );
          setCosponsors(foundCosponsors);
        }
        
        // Load explainer if available
        if (data.explainer) {
          setExplainer(data.explainer);
        }
      } catch (err) {
        console.error("Failed to load bill:", err);
        setError("Failed to load bill");
      } finally {
        setLoading(false);
      }
    }
    
    loadBill();
  }, [billId]);

  const formatDate = (dateStr: string) => {
    if (!dateStr) return "Date unavailable";
    try {
      return new Date(dateStr).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric"
      });
    } catch {
      return "Date unavailable";
    }
  };

  const getBillTypeLabel = (type: string) => {
    const labels: Record<string, string> = {
      hr: "House Bill",
      s: "Senate Bill",
      hjres: "House Joint Resolution",
      sjres: "Senate Joint Resolution",
      hconres: "House Concurrent Resolution",
      sconres: "Senate Concurrent Resolution",
      hres: "House Resolution",
      sres: "Senate Resolution"
    };
    return labels[type] || type.toUpperCase();
  };

  const copyExplainer = () => {
    if (!explainer || !bill) return;
    
    const text = `
${bill.title}
${getBillTypeLabel(bill.billType)} ${bill.billNumber} (${bill.congress}th Congress)

IN ONE SENTENCE:
${explainer.oneSentence}

WHAT IT WOULD DO:
${explainer.whatItWouldDo.map(x => `• ${x}`).join('\n')}

WHO IT AFFECTS:
${explainer.whoItAffects.map(x => `• ${x}`).join('\n')}

WHAT CHANGES IF IT PASSES:
${explainer.whatChanges.map(x => `• ${x}`).join('\n')}

KEY TERMS:
${explainer.keyTerms.map(t => `• ${t.term}: ${t.definition}`).join('\n')}

ARGUMENTS FOR:
${explainer.argumentsFor.map(x => `• ${x}`).join('\n')}

ARGUMENTS AGAINST:
${explainer.argumentsAgainst.map(x => `• ${x}`).join('\n')}

WHAT TO WATCH:
${explainer.whatToWatch}

---
Sources: ${explainer.sourcesUsed.map(s => s.url).join(', ')}
Generated by Capitol Pulse | poli-techs.us
    `.trim();
    
    navigator.clipboard.writeText(text);
    alert("Explainer copied to clipboard!");
  };

  if (loading) {
    return (
      <div className="pt-28 pb-24 min-h-screen">
        <div className="mx-auto max-w-4xl px-6">
          <div className="animate-pulse">
            <div className="h-6 bg-white/10 rounded w-32 mb-4" />
            <div className="h-12 bg-white/10 rounded w-3/4 mb-4" />
            <div className="h-64 bg-white/10 rounded-2xl" />
          </div>
        </div>
      </div>
    );
  }

  if (error || !bill) {
    return (
      <div className="pt-28 pb-24 min-h-screen">
        <div className="mx-auto max-w-4xl px-6">
          <Link href="/capitol-pulse/bills" className="text-accent-blue hover:text-accent-blue/80 text-sm mb-4 inline-block">
            ← Back to Bills
          </Link>
          <div className="bg-navy-800/40 rounded-2xl border border-white/5 p-12 text-center">
            <span className="text-6xl mb-6 block">📜</span>
            <h1 className="text-2xl font-display font-bold text-white mb-4">
              {error || "Bill Not Found"}
            </h1>
            <p className="text-white/50 mb-6">
              This bill could not be found in our database.
            </p>
            <Link 
              href="/capitol-pulse/bills"
              className="inline-block px-6 py-3 rounded-full bg-accent-blue text-white font-medium hover:bg-accent-blue/80 transition-colors"
            >
              Browse All Bills
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="pt-28 pb-24 min-h-screen">
      <div className="mx-auto max-w-4xl px-6">
        {/* Breadcrumb */}
        <ScrollReveal animation="fade-down">
          <Link href="/capitol-pulse/bills" className="text-accent-blue hover:text-accent-blue/80 text-sm mb-4 inline-block">
            ← Back to Bill Tracker
          </Link>
        </ScrollReveal>

        {/* Bill Card */}
        <ScrollReveal animation="fade-up">
          <article className="bg-navy-800/40 rounded-2xl border border-white/5 overflow-hidden">
            {/* Header */}
            <div className="p-6 border-b border-white/5">
              <div className="flex flex-wrap items-center gap-3 mb-4">
                <span className="px-3 py-1 rounded-full bg-accent-blue/20 text-accent-blue text-sm font-medium">
                  {bill.billType.toUpperCase()}.{bill.billNumber}
                </span>
                <span className="px-3 py-1 rounded-full bg-white/10 text-white/60 text-xs">
                  {bill.congress}th Congress
                </span>
                <span className="text-white/30 text-sm ml-auto">
                  Introduced {formatDate(bill.introducedDate)}
                </span>
              </div>
              
              <h1 className="text-2xl md:text-3xl font-display font-bold text-white mb-4">
                {bill.title}
              </h1>
              
              {bill.shortTitle && bill.shortTitle !== bill.title && (
                <p className="text-white/60 mb-4 italic">
                  Also known as: "{bill.shortTitle}"
                </p>
              )}
              
              {/* Topics */}
              {bill.topics.length > 0 && (
                <div className="flex flex-wrap gap-2">
                  {bill.topics.map(t => {
                    const topic = techTopics.find(tp => tp.id === t);
                    return (
                      <Link
                        key={t}
                        href={`/capitol-pulse/topics/${encodeURIComponent(t)}`}
                        className="px-3 py-1 rounded-full bg-accent-blue/10 text-accent-blue text-sm hover:bg-accent-blue/20 transition-colors"
                      >
                        {topic?.icon} {t}
                      </Link>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Latest Action */}
            <div className="p-6 border-b border-white/5 bg-gradient-to-r from-accent-blue/5 to-transparent">
              <h2 className="text-white/50 text-sm font-medium uppercase tracking-wider mb-2">
                Latest Action
              </h2>
              <p className="text-white font-medium">{bill.latestAction}</p>
              <p className="text-white/40 text-sm">{formatDate(bill.latestActionDate)}</p>
            </div>

            {/* Sponsor */}
            {sponsor && (
              <div className="p-6 border-b border-white/5">
                <h2 className="text-white/50 text-sm font-medium uppercase tracking-wider mb-3">
                  Sponsor
                </h2>
                <Link
                  href={`/capitol-pulse/members/${sponsor.bioguideId}`}
                  className="flex items-center gap-4 hover:opacity-80 transition-opacity"
                >
                  <div className={`w-12 h-12 rounded-full flex items-center justify-center text-white text-lg font-bold ${
                    sponsor.party === "Democratic" ? "bg-blue-500" :
                    sponsor.party === "Republican" ? "bg-red-500" :
                    "bg-purple-500"
                  }`}>
                    {sponsor.firstName[0]}{sponsor.lastName[0]}
                  </div>
                  <div>
                    <p className="text-white font-medium">{sponsor.name}</p>
                    <p className="text-white/50 text-sm">
                      {sponsor.chamber} ({sponsor.party.charAt(0)}) - {sponsor.state}
                    </p>
                  </div>
                </Link>
              </div>
            )}

            {/* Cosponsors */}
            {bill.cosponsorCount > 0 && (
              <div className="p-6 border-b border-white/5">
                <button
                  onClick={() => setShowCosponsors(!showCosponsors)}
                  className="w-full flex items-center justify-between"
                >
                  <h2 className="text-white/50 text-sm font-medium uppercase tracking-wider">
                    Cosponsors ({bill.cosponsorCount})
                  </h2>
                  <span className="text-accent-blue text-sm">
                    {showCosponsors ? "Hide" : "Show"}
                  </span>
                </button>
                
                {showCosponsors && cosponsors.length > 0 && (
                  <div className="mt-4 grid gap-2 max-h-64 overflow-y-auto">
                    {cosponsors.map(cs => (
                      <Link
                        key={cs.bioguideId}
                        href={`/capitol-pulse/members/${cs.bioguideId}`}
                        className="flex items-center gap-3 p-2 rounded-lg bg-white/5 hover:bg-white/10 transition-colors"
                      >
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold ${
                          cs.party === "Democratic" ? "bg-blue-500" :
                          cs.party === "Republican" ? "bg-red-500" :
                          "bg-purple-500"
                        }`}>
                          {cs.firstName[0]}{cs.lastName[0]}
                        </div>
                        <span className="text-white text-sm">{cs.name}</span>
                        <span className="text-white/40 text-xs">({cs.party.charAt(0)}-{cs.state})</span>
                      </Link>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Official Summary */}
            {bill.summary && (
              <div className="p-6 border-b border-white/5">
                <h2 className="text-white/50 text-sm font-medium uppercase tracking-wider mb-3">
                  Official Summary (from Congress.gov)
                </h2>
                <div className="text-white/70 leading-relaxed text-sm whitespace-pre-wrap">
                  {bill.summary}
                </div>
              </div>
            )}

            {/* Policy Area & Subjects */}
            {(bill.policyArea || bill.subjects.length > 0) && (
              <div className="p-6 border-b border-white/5">
                <h2 className="text-white/50 text-sm font-medium uppercase tracking-wider mb-3">
                  Policy Area & Subjects
                </h2>
                {bill.policyArea && (
                  <p className="text-white mb-2">
                    <span className="text-white/50">Policy Area:</span> {bill.policyArea}
                  </p>
                )}
                {bill.subjects.length > 0 && (
                  <div className="flex flex-wrap gap-2">
                    {bill.subjects.map(s => (
                      <span key={s} className="px-2 py-1 rounded bg-white/5 text-white/60 text-xs">
                        {s}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Why Tagged */}
            {bill.matchedSubjects && bill.matchedSubjects.length > 0 && (
              <div className="p-6 border-b border-white/5 bg-accent-blue/5">
                <h2 className="text-white/50 text-sm font-medium uppercase tracking-wider mb-3">
                  🔬 Why This Was Tagged as Tech-Related
                </h2>
                <p className="text-white/60 text-sm mb-2">
                  This bill was tagged based on these official Congress.gov subjects:
                </p>
                <div className="flex flex-wrap gap-2">
                  {bill.matchedSubjects.map(s => (
                    <span key={s} className="px-2 py-1 rounded bg-accent-blue/20 text-accent-blue text-sm">
                      {s}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Source Link */}
            <div className="p-6 bg-navy-900/50">
              <h2 className="text-white/50 text-sm font-medium uppercase tracking-wider mb-3">
                📎 Official Source
              </h2>
              <a
                href={bill.url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-accent-blue hover:text-accent-blue/80"
              >
                View on Congress.gov →
              </a>
            </div>
          </article>
        </ScrollReveal>

        {/* Plain-English Explainer */}
        <ScrollReveal animation="fade-up" delay={100}>
          <div className="mt-8 bg-gradient-to-br from-emerald-500/10 via-navy-800/40 to-accent-blue/10 rounded-2xl border border-emerald-500/20 overflow-hidden">
            <div className="p-6 border-b border-white/5">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-xl font-display font-bold text-white flex items-center gap-2">
                    📖 Plain-English Explainer
                  </h2>
                  <p className="text-white/50 text-sm">
                    What this bill actually means, in normal language
                  </p>
                </div>
                {explainer && (
                  <button
                    onClick={copyExplainer}
                    className="px-4 py-2 rounded-lg bg-white/10 text-white text-sm hover:bg-white/20 transition-colors"
                  >
                    📋 Copy
                  </button>
                )}
              </div>
            </div>

            {explainerLoading ? (
              <div className="p-6 text-center">
                <div className="animate-spin rounded-full h-8 w-8 border-2 border-emerald-500 border-t-transparent mx-auto mb-4" />
                <p className="text-white/50">Generating explainer from official sources...</p>
              </div>
            ) : explainer ? (
              <div className="divide-y divide-white/5">
                {/* One Sentence */}
                <div className="p-6">
                  <h3 className="text-emerald-400 text-sm font-medium uppercase tracking-wider mb-2">
                    In One Sentence
                  </h3>
                  <p className="text-white text-lg font-medium">
                    {explainer.oneSentence}
                  </p>
                </div>

                {/* What It Would Do */}
                <div className="p-6">
                  <h3 className="text-emerald-400 text-sm font-medium uppercase tracking-wider mb-3">
                    What It Would Do
                  </h3>
                  <ul className="space-y-2">
                    {explainer.whatItWouldDo.map((item, i) => (
                      <li key={i} className="flex gap-3 text-white/80">
                        <span className="text-emerald-400">•</span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Who It Affects */}
                <div className="p-6">
                  <h3 className="text-emerald-400 text-sm font-medium uppercase tracking-wider mb-3">
                    Who It Affects
                  </h3>
                  <ul className="space-y-2">
                    {explainer.whoItAffects.map((item, i) => (
                      <li key={i} className="flex gap-3 text-white/80">
                        <span className="text-emerald-400">•</span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* What Changes */}
                <div className="p-6">
                  <h3 className="text-emerald-400 text-sm font-medium uppercase tracking-wider mb-3">
                    What Changes If It Passes
                  </h3>
                  <ul className="space-y-2">
                    {explainer.whatChanges.map((item, i) => (
                      <li key={i} className="flex gap-3 text-white/80">
                        <span className="text-emerald-400">•</span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Key Terms */}
                {explainer.keyTerms.length > 0 && (
                  <div className="p-6">
                    <h3 className="text-emerald-400 text-sm font-medium uppercase tracking-wider mb-3">
                      Key Terms Explained
                    </h3>
                    <div className="space-y-3">
                      {explainer.keyTerms.map((term, i) => (
                        <div key={i} className="bg-white/5 rounded-lg p-3">
                          <p className="text-white font-medium">{term.term}</p>
                          <p className="text-white/60 text-sm">{term.definition}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Arguments For/Against */}
                <div className="p-6 grid md:grid-cols-2 gap-6">
                  <div>
                    <h3 className="text-emerald-400 text-sm font-medium uppercase tracking-wider mb-3">
                      Arguments For
                    </h3>
                    <ul className="space-y-2">
                      {explainer.argumentsFor.map((item, i) => (
                        <li key={i} className="flex gap-3 text-white/80 text-sm">
                          <span className="text-emerald-400">✓</span>
                          {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-red-400 text-sm font-medium uppercase tracking-wider mb-3">
                      Arguments Against
                    </h3>
                    <ul className="space-y-2">
                      {explainer.argumentsAgainst.map((item, i) => (
                        <li key={i} className="flex gap-3 text-white/80 text-sm">
                          <span className="text-red-400">✗</span>
                          {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* What to Watch */}
                <div className="p-6">
                  <h3 className="text-emerald-400 text-sm font-medium uppercase tracking-wider mb-2">
                    What to Watch Next
                  </h3>
                  <p className="text-white/80">{explainer.whatToWatch}</p>
                </div>

                {/* Sources */}
                <div className="p-6 bg-navy-900/50">
                  <h3 className="text-white/50 text-sm font-medium uppercase tracking-wider mb-3">
                    Sources Used
                  </h3>
                  <ul className="space-y-1">
                    {explainer.sourcesUsed.map((source, i) => (
                      <li key={i}>
                        <a
                          href={source.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-accent-blue hover:text-accent-blue/80 text-sm"
                        >
                          {source.title} →
                        </a>
                      </li>
                    ))}
                  </ul>
                  {explainer.disclaimers.length > 0 && (
                    <div className="mt-4 p-3 rounded-lg bg-amber-500/10 border border-amber-500/20">
                      <p className="text-amber-400 text-xs font-medium mb-1">⚠️ Limitations:</p>
                      {explainer.disclaimers.map((d, i) => (
                        <p key={i} className="text-white/50 text-xs">{d}</p>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="p-6 text-center">
                <span className="text-4xl mb-4 block">📋</span>
                <h3 className="text-white font-medium mb-2">Explainer Unavailable</h3>
                <p className="text-white/50 text-sm max-w-md mx-auto">
                  A plain-English explainer could not be generated for this bill. 
                  This may be because the official summary is not yet available on Congress.gov.
                </p>
                <a
                  href={bill.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-block mt-4 text-accent-blue hover:text-accent-blue/80 text-sm"
                >
                  Read the full bill on Congress.gov →
                </a>
              </div>
            )}
          </div>
        </ScrollReveal>

        {/* View Evidence */}
        <ScrollReveal animation="fade-up" delay={150}>
          <div className="mt-8 flex flex-wrap gap-4">
            <Link
              href={`/capitol-pulse/search?q=${encodeURIComponent(bill.title.split(' ').slice(0, 5).join(' '))}`}
              className="px-4 py-2 rounded-full bg-white/5 text-white/70 text-sm hover:bg-white/10 transition-colors"
            >
              Find related statements →
            </Link>
            {sponsor && (
              <Link
                href={`/capitol-pulse/members/${sponsor.bioguideId}`}
                className="px-4 py-2 rounded-full bg-white/5 text-white/70 text-sm hover:bg-white/10 transition-colors"
              >
                More from {sponsor.name} →
              </Link>
            )}
          </div>
        </ScrollReveal>
      </div>
    </div>
  );
}

